export enum ChildActionTypes {
  SUBSCRIBE_TO_CHILD_UPDATES = 'SUBSCRIBE_TO_CHILD_UPDATES',
  UNSUBSCRIBE_TO_CHILD_UPDATES = 'UNSUBSCRIBE_TO_CHILD_UPDATES',
  SET_UPDATE_CHANNEL = 'SET_UPDATE_CHANNEL',
  SET_CHILD_DATA = 'SET_CHILD_DATA'
}

export enum EVENT_TYPES {
  CHILD_UPDATES = 'child_updated'
}
